export default {
  urlMaps: {
    '/home': '/home',
    '/client_statistic': '/generator/client_statistic',
    '/client_detail': '/generator/client_detail',
    '/client_detail_day': '/generator/client_detail_day',
    '/unit_detail': '/generator/unit_detail',
    '/unit_detail_day': '/generator/unit_detail_day',
    '/finance_statistic': '/generator/finance_statistic',
    '/finance_analysis': '/generator/finance_analysis',
    '/finance_detail': '/generator/finance_detail',
    '/cpc_ad_income_statistic': '/generator/cpc_ad_income_statistic',
    '/cpc_ad_app_analysis': '/generator/cpc_ad_app_analysis',
    '/cpc_ad_app_analysis_day': '/generator/cpc_ad_app_analysis_day',
    '/cpc_ad_pos_analysis': '/generator/cpc_ad_pos_analysis',
    '/cpc_ad_pos_analysis_day': '/generator/cpc_ad_pos_analysis_day',
    '/cpc_ad_game': '/generator/cpc_ad_game',
    '/agent_statistic': '/generator/agent_statistic',
    '/band_statistic': '/generator/band_statistic',
    '/cpd_ad_income_statistic': '/generator/cpd_ad_income_statistic',
    '/cpd_ad_pos_analysis': '/generator/cpd_ad_pos_analysis',
    '/cpd_ad_pos_analysis_day': '/generator/cpd_ad_pos_analysis_day',
    '/cpd_ad_pos_analysis_app': '/generator/cpd_ad_pos_analysis_app',
    '/cpd_ad_app': '/generator/cpd_ad_app',
    '/cpd_ad_keyword_statistic': '/generator/cpd_ad_keyword_statistic',
    '/cpd_ad_module_analysis': '/generator/cpd_ad_module_analysis',
    '/cpd_ad_module_analysis_day': '/generator/cpd_ad_module_analysis_day',
    '/cpd_ad_module_analysis_app': '/generator/cpd_ad_module_analysis_app',
    '/cpd_ad_game': '/generator/cpd_ad_game',
    '/client_industry_analysis': '/generator/client_industry_analysis',
    '/client_industry_analysis_day': '/generator/client_industry_analysis_day',
    '/permission_resource': '/generator/permission_resource',
    '/permission_role': '/generator/permission_role',
    '/permission_user': '/generator/permission_user',
    '/module_effect': '/generator/module_effect',
    '/module_effect_app': '/generator/module_effect_app',
    '/module_special': '/generator/module_special',
    '/module_collection': '/generator/module_collection',
    '/users_active_source': '/generator/users_active_source',
    '/no_balance_game_virtual_bid': '/generator/no_balance_game_virtual_bid',
    '/account_verify': '/generator/account_verify',
    '/account_overview': '/generator/account_overview',
    '/agency_verify': '/generator/agency_verify',
    '/message': '/generator/message',
    '/fin_management': '/generator/fin_management',
    '/fin_rebate': '/generator/fin_rebate',
    '/recharge_detail': '/generator/recharge_detail',
    '/invoice_audit': '/generator/invoice_audit',
    '/algorithm': '/generator/algorithm',
    '/system_param': '/generator/system_param',
    '/basedata': '/generator/basedata',
    '/agent': '/generator/agent',
    '/ad_activity': '/generator/ad_activity',
    '/ad_module': '/generator/ad_module',
    '/ad_creative': '/generator/ad_creative',
    '/ad_resource': '/generator/ad_resource',
    '/app_black': '/generator/app_black',
    '/sponsor_black': '/generator/sponsor_black',
    '/app_cate_black': '/generator/app_cate_black',
    '/app_cert_black': '/generator/app_cert_black',
    '/help_center': '/generator/help_center',
    '/exposure_rule': '/generator/exposure_rule',
    '/app_cat_limit': '/generator/app_cat_limit',
    '/algorithm_switch': '/generator/algorithm_switch',
    '/openapi_author': '/generator/openapi_author',
    '/algorithm_set': '/generator/algorithm_set',
    '/key_black': '/generator/key_black',
    '/search_keys': '/generator/search_keys',
    '/agent_manage': '/generator/agent_manage',
    '/sponsor_manage': '/generator/sponsor_manage',
    '/long_tail': '/generator/long_tail',
    '/opin_ion': '/generator/opin_ion',
  },

  // permissionTree: {
  //   // AD: {
  //   //   title: '广告平台',
  //   //   icon: 'fa-ad',
  //   // },
  //   // BASEDATA: {
  //   //   title: '基础设置',
  //   //   icon: 'fa-database',
  //   // },
  //   // APPSTORE: {
  //   //   title: '应用商店',
  //   //   icon: 'fa-appStore',
  //   // },
  //   // FASTAPP: {
  //   //   title: '快应用',
  //   //   icon: 'fa-fastapp',
  //   // },
  //   ACCOUNT: {
  //     title: '账号管理',
  //     icon: '',
  //   },
  //   AD: {
  //     title: '广告管理',
  //     icon: '',
  //   },
  //   ANALYSIS: {
  //     title: '数据分析',
  //     icon: '',
  //   },
  //   BASEDATA: {
  //     title: '基础设置',
  //     icon: '',
  //   },
  //   EXP: {
  //     title: '实验计划',
  //     icon: '',
  //   },
  //   FINANCE: {
  //     title: '财务管理',
  //     icon: '',
  //   },
  //   MESSAGE: {
  //     title: '消息通知',
  //     icon: '',
  //   },
  //   PERMISSION: {
  //     title: '权限管理',
  //     icon: '',
  //   },
  //   // TEST: {
  //   //     title: '数据分析',
  //   //     icon: '',
  //   // },
  // },

  // 第二级跳转映射菜单
  childPage: {
    '/generator/client_detail_day': '/generator/client_detail',
    '/generator/cpc_ad_app_analysis_day': '/generator/cpc_ad_app_analysis',
    '/generator/cpc_ad_pos_analysis_day': '/generator/cpc_ad_pos_analysis',
    '/generator/agent_statistic_day': '/generator/agent_statistic',
    '/generator/agent_statistic_advertiser': '/generator/agent_statistic',
    '/generator/cpd_ad_pos_analysis_day': '/generator/cpd_ad_pos_analysis',
    '/generator/cpd_ad_pos_analysis_app': '/generator/cpd_ad_pos_analysis',
    '/generator/band_statistic_pos': '/generator/band_statistic',
    '/generator/cpd_ad_app_day': '/generator/cpd_ad_app',
    '/generator/cpd_ad_app_pos': '/generator/cpd_ad_app',
    '/generator/unit_detail_day': '/generator/unit_detail',
    '/generator/module_effect_app': '/generator/module_effect',
    '/generator/cpd_ad_module_analysis_day': '/generator/cpd_ad_module_analysis',
    '/generator/cpd_ad_module_analysis_app': '/generator/cpd_ad_module_analysis',
    '/generator/client_industry_analysis_day': '/generator/client_industry_analysis',
    '/generator/external_channel_app_day': '/generator/external_channel_app',
    '/generator/cpd_ad_game_day': '/generator/cpd_ad_game',
    '/generator/cpd_ad_game_pos': '/generator/cpd_ad_game',
    '/export_page/module_special_app': '/generator/module_special',
    '/export_page/module_ranks_pos': '/generator/module_ranks',
    '/export_page/module_ranks_app': '/generator/module_ranks',
    '/export_page/module_category_pos': '/generator/module_category',
  },
};
